### ISSUE TITLE
Error running nhl_goal_light.py on raspberry pi

### ISSUE THREAD

**Issue by arim215** [arim215/nhl_goal_light#17]
flask_api.py works good but nhl_goal_light.py give error when entering team

$ sudo python nhl_goal_light.py
Enter team you want to setup (without city) (Default: Canadiens)
Canadiens
Traceback (most recent call last):
  File "nhl_goal_light.py", line 42, in <module>
    team = input("Enter team you want to setup (without city) (Default: Canadiens) \n")
  File "<string>", line 1, in <module>
NameError: name 'Canadiens' is not defined

**Comment by francisbonneau** [comment]
Time to update to python 3 ! http://stackoverflow.com/questions/4915361/whats-the-difference-between-raw-input-and-input-in-python3-x

**Comment by arim215** [comment]
Fixed using python3
