### ISSUE TITLE
Trouble with end_game

### ISSUE THREAD

**Issue by mg3point** [arim215/nhl_goal_light#23]
As i mentioned previously I am still quite the newb when it comes to this, but for the life of me i cannot get it working. I run the flask_api and that works fine. I cleared the team id in the settings so that way i can test it with any game going on. I input the team i want, but it keeps getting hung up here...

Traceback (most recent call last):
  File "nhl_goal_light.py", line 118, in <module>
    game_end = response.json()['end_game']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

I should mention i also edited the light.py to incorporate my light function, but this to me seems erroring when its checking end game. If there was no game today it closes out fine. But at any rate my goal trigger function looks like this...  

""" Function to activate GPIO for goal light and plar random audio clip. """

    # add to def activate_goal_light
    score = requests.get("http://statsapi.web.nhl.com/api/v1/schedule?teamId=29")
    team_id = 29
    score = score.text[score.text.find('id\" : {}'.format(team_id)) - 37:score.text.find('id\" : {}'.format(team_id)) - 36]
    score = int(score)
    print(score)
    trigger_goal_lights = 'hyperion-remote -a _ipAddress_ -e Goal -d 40000'
    os.system(trigger_goal_lights)  # Play lights
    if score == 3:
        # MAKE SURE 3rd Goal audio is names 3rdgoal.mp3 in /audio folder
        command_play_song = 'sudo mpg123 -q ./audio/goal_horn_3.mp3'
    else:
        command_play_song = 'sudo mpg123 -q ./audio/goal_horn_1.mp3'
    os.system(command_play_song)  # Play sound

**Comment by mg3point** [comment]
Oddly didnt change anything and setting it up to run for the upcoming game in 30 minutes and its running fine. True test will be game time and how it responds.

**Comment by arim215** [comment]
@mg3point I'm having a bit of trouble understanding the problem... if you clear the theam_id in the settings.txt, make sure you leave an empty line. (btw, did you add "import requests" to the import list of light.py?

you can't use the custom light.py when you setup nhl_goal_light.py with another team (IF BLUE JACKETS DON'T HAVE A GAME) because the `score = requests.get("http://statsapi.web.nhl.com/api/v1/schedule?teamId=29")` will give you an error (since there is no game -> no score).

**Comment by mg3point** [comment]
So it did run for the game on saturday. Had about a 20 second delay, but thats the best i've seen so far as to trying to get it instant. It ran its checks fine all the way through. I had to leave before end of the game but let it running  and had my mac reading the prints.  Looks like it ran all the way to the end judging by the time stamps, but once it hit end game it erred out. 

Traceback (most recent call last):
  File "nhl_goal_light.py", line 129, in <module>
    new_score = response.json()['score']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

I did try it again briefly later that night with a later game that was in progress and it erred out  with the same error. ( i thought about the fact that the light.py was calling the cbj team directly but thought the error would be there then, don't think it ever got that far.

Apologies if this is becoming a pain, just trying to figure out whats going on on my end. Overall I am grateful for all your help.

CBJ have another game tonight I can run another test, unfortunately, again, i wont be able to stay home for all of it though.

**Comment by mg3point** [comment]
Set it to run 40 minutes prior to game start.  Started hitting every 2 seconds or so but then hit the same error at exactly 7:00 (30 min before game). 

Traceback (most recent call last):
  File "nhl_goal_light.py", line 129, in <module>
    new_score = response.json()['score']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 793, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Can't get it back to hitting again. Not sure if this is helpful or not.

**Comment by arim215** [comment]
I tested my ORIGINAL code (not with your modified light.py) with the penguins' game last night, it worked with no problemes and stoped at the end of the game...

**Comment by mg3point** [comment]
No problem, i'll revert back and if i ever get time, try to go about implementing more. Same goes for the other ideas. I'll let you know if i ever make any progress. Thanks for your help.

**Comment by arim215** [comment]
@mg3point ill try to setup my goal_light for columbus' game tonigh with the custom light.py i made you and see if it works. But as i said. If you use the custom light.py, you can't setup the goal_light for another team...

**Comment by mg3point** [comment]
Great night for testing, 5 goals! I reverted back to the original code with my lights added in and it seemed to work fine. Trigger ranged from 12 to 25 seconds off live tv. End game was a few mintues late, but it eventually fired and seemed to run good. Thats pretty good, best i've been able to come up with so thank you. Curious how instantaneous the budweiser ones are in comparison or if they are essentially running the same system.

**Comment by arim215** [comment]
Issue fixed. The probleme was the there was a eng_game check even when there was no game! put the end_game check after the if game_day validation
