### ISSUE TITLE
Forking Micropython Version

### ISSUE THREAD

**Issue by quarterturn** [arim215/nhl_goal_light#25]
Just letting you know I like the project and am working on a fork for ESP8266 running Micropython. The idea is to make it more foolproof with embedded hardware, as well as cheaper.

Main work in porting has involved working around datetime, as it is just too big to import on ESP8266 with its limited RAM. Mostly datetime seems to be used to calculate the 'sleeps', so I just replaced them with a fixed wait time of an hour for now.

ESP8266 has enough GPIO to allow use of DIP switches to set the team and a potentiometer to set the delay. I figure "average Joe" might be OK with visiting the hosted AP to configure their wireless info, but probably isn't going to find whatever DHCP gives it to go back and set the team and delay time.

If enough people want it, I may do a board with a 12 to 5V buck converter and a relay, so you can use whatever 12V beacon light you want.

**Comment by bing3r** [comment]
I am more curious if this can be tied into a Stringify or IFTTT applet to trigger my Philips Hue lights to flash different colors?  I have seen a few videos of individuals doing so but it looks like they did a LOT of coding and had some sort of audio synth trigger.  It sounds a lot more complicated than I thought it was going to be.

**Comment by quarterturn** [comment]
Some beta-quality code is here: 
https://github.com/quarterturn/micropython_nhl_goal_light

Hue bulbs should be doable so long as there's a way of controlling them from Linux. I have Ikea Trafri and their hub, and there are python libraries for that, but not sure on Hue as I don't have those.
