### ISSUE TITLE
NHL Goal Light Install Questions

### ISSUE THREAD

**Issue by pbouthil** [arim215/nhl_goal_light#28]
I have a question on what the function of the momentary switch is? I have the normally open switch connected to pins 9 and 11. When I press it nothing happens either when the NHL Goal Light is in ready mode or when it is running the light and audio clip. I have the NHL Goal Light installed on a Raspberry Pi 1 Model B board with Raspbian Stretch OS. Also does the switch connection need a resister in line with it?
![20210205_080839](https://user-images.githubusercontent.com/5903893/107051420-a9177780-6789-11eb-9476-e0fd95f0d46b.jpg)

**Comment by pbouthil** [comment]
Update. I did some measuring with a DVM on pin 11 (GPIO17) and there is no voltage on the pin. I am highly confuse that the push button is connected to that pin and the ground pin 9 when both pins are at the same voltage potential. I changed to pin 15 (GPIO22)  and still nothing. I see that your previous version 3.0 has the switch connected to the 3.3v (pin 17) to GPIO22 (pin 15). This is a substantial change to the GPIO Setup PDF than your current setup. Please help me understand what I am doing wrong or missing.

**Comment by pbouthil** [comment]
2nd Update: After some testing I found that the momentary switch has to be connected to pin 11 (GPIO17) and pin 17 (3.3v) for it to trigger (activate) the light and audio when the button is pushed.
![20210207_115039](https://user-images.githubusercontent.com/5903893/107157071-4962cd00-693f-11eb-9e83-9be291983446.jpg)

**Comment by arim215** [comment]
Updated the pdf. sorry for never seeing this... glad you figured it out
