### ISSUE TITLE
Version 3.1

### ISSUE THREAD

**Issue by pbouthil** [arim215/nhl_goal_light#29]
Your new code in the nhl_goal_light.py file has issues. At least for me. I updated to your latest 3.1 version and executed in terminal and it gets hung up on "do you want to update current delay". when I answer yes or no and hit enter it once again asks the same question. I can never get pasted it. I also didn't get the trigger to set off the light and audio during a goal. I am running the goal light on a 2012 Raspberry Pi 1 B w/ Stretch. Previous versions worked but this version doesn't. Please help.
![Goal light](https://user-images.githubusercontent.com/5903893/138996145-ee47617f-d475-4077-ad7e-a7b6fb0efba0.jpg)

**Comment by pbouthil** [comment]
UPDATE: I pounded out (#) lines 84 thought 90 and now the goal light is working again.

**Comment by arim215** [comment]
removed the option to try to get a better delay. back to manual delay for now...
