### ISSUE TITLE
NHL Goal Light no longer works

### ISSUE THREAD

**Issue by pbouthil** [arim215/nhl_goal_light#30]
The NHL goal light is not working. When I execute the program in terminal it displays the team chosen number and the delay number. It no longer shows the time and it definitely doesn't trigger when a goal is scored with lights and sound. It also doesn't display the score or goal on the terminal screen.

**Comment by pbouthil** [comment]
Are you no longer supporting the NHL Goal Light project? It worked awesome until the reference API website went away.

**Comment by insaneway** [comment]
> Are you no longer supporting the NHL Goal Light project? It worked awesome until the reference API website went away.

I recently started this project for myself. I took arim215's work and adapted it to the new NHL API. You can find my adaptation at https://github.com/insaneway/nhl_goal_light_2023_api

I made some improvements as well including downloading all 32 goal horns and they play dynamically based upon which team you are tracking.

**Comment by pbouthil** [comment]
Thank you so much for your response "insaneway". I'm glad that you adapted the new NHL API into your project and your willing to share. Here is my NHL Goal light project that I created with https://github.com/arim215/nhl_goal_light original code.
![20210312_113844](https://github.com/arim215/nhl_goal_light/assets/5903893/d7c691ff-4a28-46af-b239-50585188cca4)

**Comment by pbouthil** [comment]
WORKS!!! Thanks once again. I can't wait for the next game.
